# Generated by Django 5.2.1 on 2025-05-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_bloodrequest_bloodrequestdonor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestdonor',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='bloodrequestdonor',
            name='message',
        ),
    ]
