# Generated by Django 5.2.1 on 2025-05-16 19:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0003_remove_bloodrequestdonor_contact_info_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bloodrequest',
            name='bloodbank_b_blood_g_f81f34_idx',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='contact_info',
            field=models.CharField(default='N/A', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Phone number must be in international format (e.g., +1234567890).')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='message',
            field=models.TextField(default='N/A', help_text='Message from the donor to the request owner'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group', 'status'], name='bloodbank_b_blood_g_e28b46_idx'),
        ),
    ]
