# Generated by Django 5.2.1 on 2025-05-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmedia',
            name='found_item_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='lostandfound.founditemclaim'),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='lost_item_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='lostandfound.lostitemclaim'),
        ),
    ]
