# Generated by Django 5.2.1 on 2025-05-15 20:03

import lostandfound.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_itemmedia_found_item_claim_itemmedia_lost_item_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='approximate_time',
            field=models.TimeField(blank=True, help_text='Approximate time the item was found (e.g., 14:30)', null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='approximate_time',
            field=models.TimeField(blank=True, help_text='Approximate time the item was lost (e.g., 14:30)', null=True),
        ),
        migrations.AlterField(
            model_name='itemmedia',
            name='id',
            field=models.CharField(default=lostandfound.models.generate_random_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
