# Generated by Django 5.2.1 on 2025-05-16 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_founditem_approximate_time_lostitem_approximate_time_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='founditem',
            name='lostandfoun_univers_5275b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='lostitem',
            name='lostandfoun_univers_d75787_idx',
        ),
        migrations.AddField(
            model_name='founditem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['university', 'status', 'approval_status'], name='lostandfoun_univers_d9efb1_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['university', 'status', 'approval_status'], name='lostandfoun_univers_e2984c_idx'),
        ),
    ]
