# Generated by Django 5.2.1 on 2025-05-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_place_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.TextField(blank=True)),
                ('place_type', models.CharField(choices=[('university', 'University'), ('department', 'Department'), ('institute', 'Institute'), ('none', 'None')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='universities.academicunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='places.place')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='universities.university')),
                ('tags', models.ManyToManyField(blank=True, related_name='places', to='places.placetag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='placetag',
            index=models.Index(fields=['name'], name='places_plac_name_1a9d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['university', 'place_type'], name='places_plac_univers_f30b59_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['parent'], name='places_plac_parent__e3ca97_idx'),
        ),
    ]
