# Generated by Django 5.2.1 on 2025-05-17 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='relative_location',
            field=models.CharField(blank=True, help_text="Descriptive location, e.g., 'Near the main library'", max_length=255),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='places_plac_latitud_09f61a_idx'),
        ),
    ]
