# Generated by Django 5.2.1 on 2025-05-17 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_latitude_place_longitude_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='places/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('relative_location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('maps_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='placetag',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_univers_f30b59_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_latitud_09f61a_idx',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('university', 'name')},
        ),
        migrations.AddField(
            model_name='place',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the place', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='history',
            field=models.TextField(blank=True, help_text='Historical background of the place'),
        ),
        migrations.AddField(
            model_name='place',
            name='maps_link',
            field=models.URLField(blank=True, help_text='Link to Google Maps or similar', max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='academic_unit',
            field=models.ForeignKey(blank=True, help_text='The academic unit this place is associated with, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='universities.academicunit'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geographical latitude', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geographical longitude', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent place in the hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='places.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='relative_location',
            field=models.CharField(blank=True, help_text="Relative location description (e.g., 'Next to Main Hall')", max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='university',
            field=models.ForeignKey(help_text='The university this place belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='universities.university'),
        ),
        migrations.AddField(
            model_name='placemedia',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='places.place'),
        ),
        migrations.AddField(
            model_name='placemedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_place_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='placetype',
            index=models.Index(fields=['name'], name='places_plac_name_f5d0d9_idx'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(help_text='Type of place (e.g., Library, Classroom)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.placetype'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['university', 'name'], name='places_plac_univers_40c20f_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_type'], name='places_plac_place_t_fc484a_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['approval_status'], name='places_plac_approva_16d54c_idx'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='academic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.academicunit'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_children', to='places.place'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='places.place'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='place_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.placetype'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placemedia',
            name='place_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='places.placeupdate'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='placeupdate',
            index=models.Index(fields=['place', 'approval_status'], name='places_plac_place_i_1389d4_idx'),
        ),
        migrations.AddIndex(
            model_name='placeupdate',
            index=models.Index(fields=['updated_by'], name='places_plac_updated_aebaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='placemedia',
            index=models.Index(fields=['place'], name='places_plac_place_i_6fda68_idx'),
        ),
        migrations.AddIndex(
            model_name='placemedia',
            index=models.Index(fields=['place_update'], name='places_plac_place_u_82a733_idx'),
        ),
        migrations.DeleteModel(
            name='PlaceTag',
        ),
    ]
