# Generated by Django 5.2.1 on 2025-05-17 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placemedia_placetype_placeupdate_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the place was established', null=True),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the place was established', null=True),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['academic_unit'], name='places_plac_academi_202aea_idx'),
        ),
    ]
