# Generated by Django 5.2.1 on 2025-05-17 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_establishment_year_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='academic_unit_root',
            field=models.BooleanField(default=False, help_text='Indicates if this place is the root of an academic unit subtree'),
        ),
        migrations.AddField(
            model_name='place',
            name='university_root',
            field=models.BooleanField(default=False, help_text='Indicates if this place is the root of the university tree'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='academic_unit_root',
            field=models.BooleanField(default=False, help_text='Indicates if this place is the root of an academic unit subtree'),
        ),
        migrations.AddField(
            model_name='placeupdate',
            name='university_root',
            field=models.BooleanField(default=False, help_text='Indicates if this place is the root of the university tree'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['university_root'], name='places_plac_univers_dfa892_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['academic_unit_root'], name='places_plac_academi_0395e7_idx'),
        ),
        migrations.AddIndex(
            model_name='placeupdate',
            index=models.Index(fields=['university_root'], name='places_plac_univers_db5431_idx'),
        ),
        migrations.AddIndex(
            model_name='placeupdate',
            index=models.Index(fields=['academic_unit_root'], name='places_plac_academi_d9f9a0_idx'),
        ),
    ]
