# Generated by Django 5.2.1 on 2025-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_academic_unit_root_place_university_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='relative_location',
            field=models.CharField(blank=True, help_text='Relative location description', max_length=255),
        ),
        migrations.AlterField(
            model_name='placeupdate',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
