# Generated by Django 5.2.1 on 2025-05-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_relative_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
    ]
