# Generated by Django 5.2.1 on 2025-05-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_level',
            field=models.CharField(choices=[('none', 'No Admin'), ('university', 'University Admin'), ('app', 'App-Wide Admin')], default='none', max_length=20),
        ),
    ]
